import './globals.css';
import type { Metadata } from 'next';
import Navbar from './_components/navbar';
import Lorem from './_components/lorem';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="relative">
        <Lorem />
        <Navbar />
        {children}
      </body>
    </html>
  )
}
