import './globals.css';
import type { Metadata } from 'next';
import Navbar from './_components/navbar';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="relative bg-surface w-full min-h-screen h-max flex flex-col overflow-y-scroll scroll-pt-[2rem] snap-y snap-mandatory">
        <Navbar />
        {children}
      </body>
    </html>
  )
}
